Repository ember-fastboot/fastboot-app-server, pull requests merged in 2020-10, with the labels that each got.

#124 Update FastBoot v3
  README.md
  package.json
  src/fastboot-app-server.js
  src/worker.js
  test/fixtures/dist-path-change-server.js
  test/fixtures/sandbox-globals-app-server.js
  yarn.lock
Labels: breaking

#114 Add link to fastboot-gcloud-storage-downloader in README
  README.md
Labels: documentation

#106 Add link to s3-notifier
  README.md
Labels: documentation

#125 Add release automation.
  RELEASE.md
  package.json
  yarn.lock
Labels: internal

#126 Migrate to GitHub Actions.
  .github/workflows/ci.yml
  .travis.yml
Labels: internal

#127 Update dependencies to latest.
  package.json
  yarn.lock
Labels: internal

#129 Update mocha to latest.
  package.json
  yarn.lock
Labels: internal

#128 Update linting setup
  .mocharc.js
  package.json
  yarn.lock
Labels: internal
